micronaut:
  application:
    name: fretesRest
  server:
    port: 8081
grpc:
  client:
      plaintext: true
      max-retry-attempts: 10
  channels:
    fretes:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10